// @ts-nocheck
import { useEffect, useMemo, useRef, useState } from 'react';
import { Link, Route, Routes, useNavigate, useSearchParams } from 'react-router-dom';
import QRCode from 'qrcode';
import type { DataConnection } from 'peerjs';
import { addLog, addSheet, assignNumbers, bump, createGame, publicState, rangeHint, scoreSheets, ticketValue } from './game';
import { boardChannel, ClientNetwork, HostNetwork } from './network';
import type { ClientMessage, ContactRoom, Difficulty, GameState, GuessSheet, HostMessage, PublicState, TicketType } from './types';
import { avatarPath, GuideEnhanced, IntroEnhanced, playSfx, SetupEnhanced, SoundLayer } from './enhancements';

const A='/assets/';
const avatar=avatarPath;
const uid=()=>crypto.randomUUID();
const loadGame=():GameState|null=>{try{return JSON.parse(sessionStorage.getItem('secret-number-game')||'null')}catch{return null}};
const saveGame=(s:GameState)=>sessionStorage.setItem('secret-number-game',JSON.stringify(s));

function Modal({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}){return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="modal"><button className="x" onClick={onClose}>×</button><h2>{title}</h2>{children}</section></div>}

function Home(){const nav=useNavigate();const [guide,setGuide]=useState(false);const [intro,setIntro]=useState(false);return <main className="home"><div className="eyebrow">더 지니어스 한 학급 놀이</div><img className="logo" src={`${A}images/logo/logo.png`}/><div className="curriculum">초등 5학년 2학기 수의 범위와 어림하기<br/><span>초등 창체·수학 시간을 활용한 추론, 의사소통, 문제해결력 신장 활동</span></div><div className="actions"><button className="primary" onClick={()=>setIntro(true)}>게임 시작</button><button onClick={()=>setGuide(true)}>사용설명서</button></div>{guide&&<GuideEnhanced onClose={()=>setGuide(false)}/>} {intro&&<IntroEnhanced onDone={()=>nav('/setup')} onClose={()=>setIntro(false)}/>}</main>}
function Guide({onClose}:{onClose:()=>void}){const [p,setP]=useState(0);const slides=[['게임 소개','다른 플레이어와 콘택트하며 자신과 친구들의 비밀 숫자를 추리합니다. 최종 점수가 가장 높은 플레이어가 우승합니다.'],['게임 사전 설정','플레이어·게임 시간을 설정하고 전광판을 교실 화면에 엽니다. 콘택트룸 주소를 태블릿 2대씩 열어 같은 티켓을 제출합니다.'],['게임 운영 방법','더하기는 두 수의 합, 곱하기는 곱의 일의 자리, 나누기는 큰 수를 작은 수로 나눈 몫, 0 티켓은 두 수 사이에 등장하는 0의 개수를 알려줍니다.'],['결과 제출과 공개','운영자가 게임을 종료하면 학생들이 QR로 답안을 제출합니다. 전원 제출 후 결과 공개를 누르면 점수와 순위가 전광판에 나타납니다.'],['참고 영상','더 자세한 진행 방식은 유튜브에서 ‘데블스 플랜 시크릿 넘버’를 검색해 참고해 주세요.']];return <Modal title={slides[p][0]} onClose={onClose}><div className="guide-visual">{p+1}</div><p className="lead">{slides[p][1]}</p>{p===4&&<a className="button" target="_blank" href="https://www.youtube.com/results?search_query=데블스+플랜+시크릿+넘버">유튜브에서 찾아보기</a>}<div className="pager"><button disabled={!p} onClick={()=>setP(p-1)}>이전</button><span>{p+1} / 5</span><button onClick={()=>p===4?onClose():setP(p+1)}>{p===4?'닫기':'다음'}</button></div></Modal>}
function Intro({onDone,onClose}:{onDone:()=>void;onClose:()=>void}){const [p,setP]=useState(0),[ok,setOk]=useState(false);const quizzes=[['24 이상 25 미만인 자연수는?',['23','24','25'],'24'],['36 초과 38 미만인 자연수는?',['36','37','38'],'37'],['51 초과 52 이하인 자연수는?',['51','52','53'],'52']];return <Modal title="수의 범위를 이해하라" onClose={onClose}><button className="skip" onClick={onDone}>인트로 건너뛰기</button>{p===0?<div className="concepts">{[['이상','기준 수 포함 · 그보다 큰 수'],['이하','기준 수 포함 · 그보다 작은 수'],['초과','기준 수 미포함 · 그보다 큰 수'],['미만','기준 수 미포함 · 그보다 작은 수']].map(x=><article><b>{x[0]}</b><span>{x[1]}</span></article>)}</div>:p<4?<div className="quiz"><h3>{quizzes[p-1][0]}</h3>{quizzes[p-1][1].map(a=><button onClick={()=>setOk(a===quizzes[p-1][2])}>{a}</button>)}{ok&&<p className="success">정답입니다. 기준 수의 포함 여부를 확인하세요.</p>}</div>:<div className="final-copy">수의 범위를 모두 알았다면, 이제 게임을 시작하지.<br/>비밀 숫자를 맞히지 못한다면 넌 이곳에서 빠져나갈 수 없다!!</div>}<div className="pager"><button disabled={!p} onClick={()=>{setP(p-1);setOk(false)}}>이전</button>{p===4?<button className="primary" onClick={onDone}>시크릿 넘버 시작</button>:<button disabled={p>0&&!ok} onClick={()=>{setP(p+1);setOk(false)}}>다음</button>}</div></Modal>}

function Setup(){const nav=useNavigate();const [names,setNames]=useState('김민준\n이서준\n박지호\n최유진\n정하린\n윤도현');const [minutes,setMinutes]=useState(60);const [difficulty,setDifficulty]=useState<Difficulty>('medium');const [rooms,setRooms]=useState(2);const list=names.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);function start(){if(list.length<2)return;const g=createGame(list,minutes,difficulty,rooms);saveGame(g);nav('/host')}return <Page title="게임 사전 설정"><a className="display-launch" href="/board" target="_blank">게임 전광판 페이지 활성화 ↗</a><div className="setup-grid"><section className="panel"><h2>플레이어 등록 <small>{list.length}/30</small></h2><textarea value={names} onChange={e=>setNames(e.target.value)} placeholder="한 줄에 한 명씩 입력하세요"/><p>최소 2명, 최대 30명까지 등록할 수 있습니다.</p></section><section className="panel options"><h2>GAME OPTION</h2><label>게임 시간<input className="time-input" type="number" min="5" max="180" value={minutes} onChange={e=>setMinutes(+e.target.value)}/><span>분</span></label><p>60분 정도가 적당합니다.<br/>학급 상황에 맞게 타이머를 조정해주세요.</p><h3>번호 난이도</h3><div className="seg">{([['high','상'],['medium','중'],['low','하']] as const).map(([v,t])=><button className={difficulty===v?'on':''} onClick={()=>setDifficulty(v)}>{t}</button>)}</div><h3>콘택트룸 수</h3><div className="seg">{[1,2,3].map(v=><button className={rooms===v?'on':''} onClick={()=>setRooms(v)}>{v}</button>)}</div></section></div><button className="primary next" onClick={start}>다음 · 비밀 카드 배정</button></Page>}
function Page({title,children}:{title:string;children:React.ReactNode}){return <main className="page"><header><Link to="/" className="home-link">메인화면</Link><h1>{title}</h1></header>{children}</main>}

function DrawScreen({state,onChange}:{state:GameState;onChange:(state:GameState)=>void}){const [shuffling,setShuffling]=useState(!state.players[0]?.secretNumber);const [countdown,setCountdown]=useState<string>();const started=useRef(false);const assigned=Boolean(state.players[0]?.secretNumber);useEffect(()=>{if(assigned||started.current)return;started.current=true;playSfx('move');const second=setTimeout(()=>playSfx('move'),1150);const finish=setTimeout(()=>{onChange(assignNumbers(state));setShuffling(false)},2300);return()=>{clearTimeout(second);clearTimeout(finish)}},[]);function startGame(){if(countdown)return;setCountdown('3');setTimeout(()=>setCountdown('2'),700);setTimeout(()=>setCountdown('1'),1400);setTimeout(()=>{setCountdown('START');playSfx('start')},2100);setTimeout(()=>onChange(bump(state,{phase:'active',timerRunning:true,logs:addLog(state,'start','게임을 시작했습니다.')})),3000)}return <Page title="비밀 카드 일괄 배정"><a className="display-launch draw-launch" href={`/board?code=${state.roomCode}`} target="_blank">게임 전광판 페이지 활성화 ↗</a><div className={`deck-stage ${shuffling?'is-shuffling':''}`}><div className="deck">{Array.from({length:12},(_,i)=><img key={i} style={{'--i':i} as React.CSSProperties} src={`${A}images/cards/card-back.png`}/>)}</div>{assigned&&<div className="assigned">{state.players.map((p,i)=><div key={p.id} style={{animationDelay:`${i*70}ms`}}><img src={`${A}images/cards/card-back.png`}/><span>{p.name}</span></div>)}</div>}</div>{shuffling?<div className="draw-status">카드를 섞고 자동 배정하는 중…</div>:assigned&&<button className="primary next" onClick={startGame}>게임 시작</button>}{countdown&&<div className={`countdown-overlay ${countdown==='START'?'start':''}`}>{countdown}</div>}</Page>}

function Host(){const nav=useNavigate();const [state,setStateRaw]=useState<GameState|null>(loadGame);const [connected,setConnected]=useState(0);const [confirmEnd,setConfirmEnd]=useState(false);const [selected,setSelected]=useState<string>();const network=useRef<HostNetwork>();const processed=useRef(new Set<string>());
  const setState=(next:GameState|((s:GameState)=>GameState))=>setStateRaw(prev=>{if(!prev)return prev;const value=typeof next==='function'?next(prev):next;saveGame(value);boardChannel.postMessage(publicState(value));network.current?.broadcast({type:'STATE',state:publicState(value)});return value});
  useEffect(()=>{if(!state)return;const net=new HostNetwork(state.roomCode);network.current=net;net.onStatus=setConnected;net.onMessage=(m,c)=>handle(m,c);boardChannel.postMessage(publicState(state));return()=>net.destroy()},[]);
  useEffect(()=>{if(!state?.timerRunning)return;const timer=setInterval(()=>setState(s=>s.remainingSeconds<=1?bump(s,{remainingSeconds:0,timerRunning:false,phase:'submission'}):bump(s,{remainingSeconds:s.remainingSeconds-1})),1000);return()=>clearInterval(timer)},[state?.timerRunning]);
  function handle(m:ClientMessage,c:DataConnection){if(!state)return;if(m.type==='HELLO'){let seat:number|undefined;if(m.role==='station'&&m.roomId){setState(s=>{const rooms=s.rooms.map(r=>{if(r.id!==m.roomId)return r;seat=r.seats.findIndex(x=>!x.deviceId||x.deviceId===m.deviceId);if(seat<0){netSend(c,{type:'ERROR',message:'이 콘택트룸에는 이미 태블릿 2대가 접속했습니다.'});return r}const seats=[...r.seats] as ContactRoom['seats'];seats[seat]={...seats[seat],deviceId:m.deviceId};return {...r,seats,status:'choosing' as const}});return bump(s,{rooms})});}netSend(c,{type:'WELCOME',state:publicState(state),seat});return}if('requestId'in m&&processed.current.has(m.requestId)){netSend(c,{type:'ACK',requestId:m.requestId,ok:true});return}if('requestId'in m)processed.current.add(m.requestId);
    if(m.type==='SELECT_PLAYER'||m.type==='SELECT_TICKET'){setState(s=>bump(s,{rooms:s.rooms.map(r=>{if(r.id!==m.roomId)return r;const seats=[...r.seats] as ContactRoom['seats'];seats[m.seat]={...seats[m.seat],...(m.type==='SELECT_PLAYER'?{playerId:m.playerId}:{ticket:m.ticket}),ready:false};return {...r,seats,status:'choosing',result:undefined,updatedAt:Date.now()}})}));netSend(c,{type:'ACK',requestId:m.requestId,ok:true});}
    if(m.type==='SUBMIT_CONTACT')resolveContact(m.roomId,m.requestId,c);if(m.type==='SUBMIT_SHEET'){setState(s=>addSheet(s,m.sheet));netSend(c,{type:'ACK',requestId:m.requestId,ok:true})}}
  function netSend(c:DataConnection,m:HostMessage){network.current?.send(c,m)}
  function resolveContact(roomId:number,requestId:string,c:DataConnection){setState(s=>{const room=s.rooms.find(r=>r.id===roomId);if(!room)return s;const [a,b]=room.seats;if(!a.playerId||!b.playerId||!a.ticket||!b.ticket)return s;if(a.ticket!==b.ticket){netSend(c,{type:'ACK',requestId,ok:false,message:'같은 티켓을 선택해주세요.'});return s}const pa=s.players.find(p=>p.id===a.playerId)!,pb=s.players.find(p=>p.id===b.playerId)!;if(pa.tickets[a.ticket]<1||pb.tickets[b.ticket]<1)return s;const n=ticketValue(a.ticket,pa.secretNumber!,pb.secretNumber!),result=rangeHint(n);const players=s.players.map(p=>p.id===pa.id||p.id===pb.id?{...p,tickets:{...p.tickets,[a.ticket]:p.tickets[a.ticket]-1}}:p);const rooms=s.rooms.map(r=>r.id===roomId?{...r,status:'result' as const,result,updatedAt:Date.now()}:r);netSend(c,{type:'ACK',requestId,ok:true});return bump(s,{players,rooms,logs:addLog(s,'contact',`${pa.name} · ${pb.name}: ${result}`,[pa.id,pb.id])})})}
  if(!state)return <Page title="게임 없음"><p>먼저 게임을 설정해주세요.</p><Link className="button" to="/setup">설정하기</Link></Page>;
  const time=`${String(Math.floor(state.remainingSeconds/60)).padStart(2,'0')}:${String(state.remainingSeconds%60).padStart(2,'0')}`;
  if(state.phase==='draw')return <DrawScreen state={state} onChange={setState}/>;
  const submitUrl=`${location.origin}/submit?code=${state.roomCode}`;return <HostDashboard state={state} time={time} submitUrl={submitUrl} selected={selected} confirmEnd={confirmEnd} onSelect={setSelected} onClosePlayer={()=>setSelected(undefined)} onConfirmEnd={setConfirmEnd} onChange={setState} onReset={()=>{sessionStorage.removeItem('secret-number-game');nav('/')}}/>}

function HostDashboard({state,time,submitUrl,selected,confirmEnd,onSelect,onClosePlayer,onConfirmEnd,onChange,onReset}:any){return <main className="page host-page"><div className="host-titlebar"><h1>{state.phase==='results'?'최종 결과':'게임 진행 센터'}</h1><button onClick={()=>onConfirmEnd(true)}>메인화면 (게임 초기화)</button></div>{state.phase==='active'&&<section className="game-control-grid"><div className="timer-console"><small>GAME IN PROGRESS</small><b className="clock">{time}</b><div><button className={state.timerRunning?'':'resume'} onClick={()=>onChange(bump(state,{timerRunning:!state.timerRunning}))}>{state.timerRunning?'일시정지':'재생'}</button><button onClick={()=>onChange(bump(state,{remainingSeconds:state.durationSeconds}))}>리셋</button></div></div><aside className="connection-console"><small>DISPLAY & CONTACT</small><a href={`/board?code=${state.roomCode}`} target="_blank">전광판 열기 ↗</a>{state.rooms.map((room:ContactRoom)=><a key={room.id} href={`/station?code=${state.roomCode}&room=${room.id}`} target="_blank">콘택트룸 {room.id} 열기 ↗</a>)}</aside></section>}{state.phase==='submission'&&<SubmissionAdmin state={state} url={submitUrl} onReveal={()=>onChange(scoreSheets(state))}/>}<PlayerGrid state={state} selected={selected} onSelect={onSelect}/>{state.phase==='active'&&<section className="end-game-panel"><div><small>END GAME</small><h2>게임 종료 및 결과지 제출</h2><p>게임을 종료하면 학생용 제출 링크를 공유할 수 있습니다.</p></div><button className="danger" onClick={()=>onConfirmEnd(true)}>게임 종료</button></section>}{state.phase==='results'&&<Ranking state={state}/>} {selected&&<PlayerDetail state={state} id={selected} onClose={onClosePlayer}/>} {confirmEnd&&<Modal title="게임을 종료하시겠습니까?" onClose={()=>onConfirmEnd(false)}><p>타이머와 콘택트가 중지되고 결과지 제출이 활성화됩니다.</p><div className="pager"><button onClick={()=>onConfirmEnd(false)}>취소</button><button className="danger" onClick={()=>{onChange(bump(state,{phase:'submission',timerRunning:false}));onConfirmEnd(false)}}>게임 종료</button><button onClick={onReset}>초기화</button></div></Modal>}</main>}

function PlayerGrid({state,selected,onSelect}:{state:GameState;selected?:string;onSelect:(x:string)=>void}){return <section className="panel"><h2>플레이어 현황 {state.phase==='submission'&&<small>{state.submissions.length}/{state.players.length} 제출</small>}</h2><div className="players">{state.players.map((p,i)=><button className={`${p.submitted?'submitted':''} ${selected===p.id?'selected':''}`} onClick={()=>onSelect(p.id)}><img src={avatar(i)}/><strong>{p.name}</strong>{p.submitted&&<span>결과 제출 완료</span>}</button>)}</div></section>}
function PlayerDetail({state,id,onClose}:{state:GameState;id:string;onClose:()=>void}){const p=state.players.find(x=>x.id===id)!;const logs=state.logs.filter(x=>x.playerIds?.includes(id));const sheet=state.submissions.find(x=>x.playerId===id);return <Modal title={p.name} onClose={onClose}><div className="secret">비밀 숫자 <b>{p.secretNumber}</b></div><h3>플레이 기록</h3>{logs.map(x=><p>{new Date(x.at).toLocaleTimeString()} · {x.text}</p>)}{sheet&&<p>내 번호 예상: {sheet.ownGuess}</p>}</Modal>}
function SubmissionAdmin({state,url,onReveal}:{state:GameState;url:string;onReveal:()=>void}){const [qr,setQr]=useState('');useEffect(()=>{QRCode.toDataURL(url,{width:280,margin:2}).then(setQr)},[url]);return <section className="submission-admin"><div><h2>학생용 결과지 제출</h2><a href={url} target="_blank">{url}</a></div>{qr&&<img src={qr}/>}<button className="primary" disabled={state.submissions.length!==state.players.length} onClick={onReveal}>결과 공개</button></section>}
function Ranking({state}:{state:GameState}){return <section className="ranking"><h2>최종 결과</h2>{[...state.players].sort((a,b)=>b.score-a.score).map((p,i)=><article className={i<3?'podium':''}>{i<3&&<img src={`${A}images/medals/medal-${['1st','2nd','3rd'][i]}.png`}/>}<b>{i+1}위</b><strong>{p.name}</strong><em>{p.score}점</em><span>↗</span></article>)}</section>}

function Board(){const [state,setState]=useState<PublicState|null>(null);const [playing,setPlaying]=useState(true);useEffect(()=>{boardChannel.onmessage=e=>setState(e.data);return()=>{boardChannel.onmessage=null}},[]);useEffect(()=>{const a=document.querySelector<HTMLAudioElement>('#board-bgm');if(!a)return;playing?a.play().catch(()=>setPlaying(false)):a.pause()},[playing,state?.phase]);if(!state)return <Page title="게임 전광판"><div className="waiting">운영 페이지에서 게임을 설정하고 이 화면을 다시 열어주세요.</div></Page>;const time=`${String(Math.floor(state.remainingSeconds/60)).padStart(2,'0')}:${String(state.remainingSeconds%60).padStart(2,'0')}`;return <main className={`board ${state.phase==='results'?'celebrate':''}`}><audio id="board-bgm" loop src={`${A}audio/bgm/${state.phase==='results'?'bgm-final-ranking.mp3':state.phase==='active'?'bgm-gameplay.mp3':'bgm-waiting.mp3'}`}/><div className="board-clock">{state.phase==='submission'?'결과지 제출 중':time}</div><div className="board-players">{state.players.map((p,i)=><article className={p.submitted?'submitted':''}><img src={avatar(i)}/><strong>{p.name}</strong>{p.submitted&&<span>결과 제출 완료</span>}</article>)}</div><div className="board-rooms">{state.rooms.map(r=><article><b>CONTACT ROOM {r.id}</b><span>{r.status==='waiting'?'대기 중':r.status==='result'?r.result:'사용 중'}</span></article>)}</div><button className="audio-control" onClick={()=>setPlaying(!playing)}>{playing?'Ⅱ':'▶'} BGM</button>{state.phase==='results'&&<Ranking state={{...state,submissions:[]} as GameState}/>}</main>}

function Station(){const [q]=useSearchParams();const code=q.get('code')||'';const roomId=+(q.get('room')||1);const device=useMemo(()=>localStorage.getItem(`station-${code}-${roomId}`)||uid(),[]);const [state,setState]=useState<PublicState|null>(null),[room,setRoom]=useState<ContactRoom>(),[seat,setSeat]=useState<number>(),[connected,setConnected]=useState(false),[message,setMessage]=useState('');const net=useRef<ClientNetwork>();useEffect(()=>{localStorage.setItem(`station-${code}-${roomId}`,device);const n=new ClientNetwork(code,{type:'HELLO',role:'station',deviceId:device,roomId});net.current=n;n.onStatus=setConnected;n.onMessage=m=>{if(m.type==='WELCOME'){setState(m.state);setSeat(m.seat);setRoom(m.state.rooms.find(r=>r.id===roomId))}if(m.type==='STATE'){setState(m.state);setRoom(m.state.rooms.find(r=>r.id===roomId))}if(m.type==='ROOM')setRoom(m.room);if(m.type==='ERROR')setMessage(m.message);if(m.type==='ACK'&&!m.ok)setMessage(m.message||'처리할 수 없습니다.')};return()=>n.destroy()},[]);const send=(m:ClientMessage)=>net.current?.send(m);if(!code)return <Page title="콘택트룸">게임 코드가 필요합니다.</Page>;return <main className="station"><header><h1>CONTACT ROOM {roomId}</h1><span className={connected?'online':'offline'}>{connected?'연결됨':'연결 중'}</span></header>{message&&<div className="notice" onClick={()=>setMessage('')}>{message}</div>}{seat===undefined?<div className="waiting">접속 자리를 확인하고 있습니다.</div>:<div className="station-layout"><section><h2>플레이어 선택</h2><div className="station-players">{state?.players.map((p,i)=><button className={room?.seats[seat].playerId===p.id?'on':''} onClick={()=>send({type:'SELECT_PLAYER',roomId,seat,playerId:p.id,requestId:uid()})}><img src={avatar(i)}/>{p.name}</button>)}</div></section><section><h2>같은 티켓을 선택하세요</h2><div className="tickets">{(['plus','multiply','divide','zero'] as TicketType[]).map(t=><button className={room?.seats[seat].ticket===t?'on':''} onClick={()=>send({type:'SELECT_TICKET',roomId,seat,ticket:t,requestId:uid()})}><img src={`${A}images/tickets/ticket-${t}.png`}/><span>{{plus:'더하기',multiply:'곱하기',divide:'나누기',zero:'0 티켓'}[t]}</span></button>)}</div><div className="station-actions"><button onClick={()=>room&&setRoom({...room,seats:room.seats.map((s,i)=>i===seat?{...s,ticket:undefined}:s) as ContactRoom['seats']})}>다시 고르기</button><button className="primary" onClick={()=>send({type:'SUBMIT_CONTACT',roomId,requestId:uid()})}>제출</button></div>{room?.status==='result'&&<div className="contact-result"><span>연산 결과</span><b>{room.result}</b></div>}</section></div>}</main>}

function Submit(){const [q]=useSearchParams();const code=q.get('code')||'';const [state,setState]=useState<PublicState|null>(null),[chosen,setChosen]=useState<string>(),[own,setOwn]=useState(''),[guesses,setGuesses]=useState<Record<string,string>>({}),[done,setDone]=useState(false),[connected,setConnected]=useState(false);const net=useRef<ClientNetwork>();useEffect(()=>{const n=new ClientNetwork(code,{type:'HELLO',role:'submission',deviceId:uid()});net.current=n;n.onStatus=setConnected;n.onMessage=m=>{if(m.type==='WELCOME'||m.type==='STATE')setState(m.state);if(m.type==='ACK'&&m.ok){setDone(true);setTimeout(()=>window.close(),800)}};return()=>n.destroy()},[]);function submit(){if(!chosen)return;const sheet:GuessSheet={playerId:chosen,ownGuess:+own,guesses:Object.fromEntries(Object.entries(guesses).map(([k,v])=>[k,+v])),submittedAt:Date.now()};net.current?.send({type:'SUBMIT_SHEET',sheet,requestId:uid()})}if(done)return <main className="submit"><div className="done">결과지 제출 완료<br/><small>이 창을 닫아도 됩니다.</small></div></main>;return <main className="submit"><header><h1>추리 결과지 제출</h1><span>{connected?'교사 기기와 연결됨':'연결 중'}</span></header>{!chosen?<section><h2>제출자를 선택하세요</h2><div className="chooser">{state?.players.filter(p=>!p.submitted).map((p,i)=><button onClick={()=>setChosen(p.id)}><img src={avatar(i)}/>{p.name}</button>)}</div></section>:<section><h2>다른 친구들의 비밀번호를 추리해 보세요.</h2><div className="own-guess"><b>내 비밀 숫자 예상</b><input inputMode="numeric" value={own} onChange={e=>setOwn(e.target.value)}/><small>내 번호를 맞히면 +5점</small></div><div className="guess-grid">{state?.players.filter(p=>p.id!==chosen).map((p,i)=><label><img src={avatar(i)}/><b>{p.name}</b><input inputMode="numeric" value={guesses[p.id]||''} onChange={e=>setGuesses({...guesses,[p.id]:e.target.value})}/><small>정답 +3점 · 내 번호 노출 시 -1점</small></label>)}</div><button className="primary next" onClick={submit}>결과지 제출</button></section>}</main>}

export default function App(){return <><SoundLayer/><Routes><Route path="/" element={<Home/>}/><Route path="/setup" element={<SetupEnhanced/>}/><Route path="/host" element={<Host/>}/><Route path="/board" element={<Board/>}/><Route path="/station" element={<Station/>}/><Route path="/submit" element={<Submit/>}/><Route path="*" element={<Home/>}/></Routes></>}
