import { useEffect,useMemo,useState } from 'react';
import { boardChannel } from './network';
import { avatarPath } from './enhancements';
import type { PublicState } from './types';
const A='/assets/';
const read=():PublicState|null=>{try{return JSON.parse(localStorage.getItem('secret-number-board-state')||'null')}catch{return null}};
export default function BoardEnhanced(){const[state,setState]=useState<PublicState|null>(read);const[playing,setPlaying]=useState(true),[selected,setSelected]=useState<string>();
  useEffect(()=>{const receive=(value:PublicState)=>{setState(value);localStorage.setItem('secret-number-board-state',JSON.stringify(value))};boardChannel.onmessage=e=>receive(e.data);const storage=(e:StorageEvent)=>{if(e.key==='secret-number-board-state'&&e.newValue)receive(JSON.parse(e.newValue))};window.addEventListener('storage',storage);const poll=setInterval(()=>{const current=read();if(current&&current.version!==(state?.version||0))setState(current)},1500);return()=>{boardChannel.onmessage=null;window.removeEventListener('storage',storage);clearInterval(poll)}},[state?.version]);
  useEffect(()=>{const audio=document.querySelector<HTMLAudioElement>('#board-bgm');if(!audio)return;playing?audio.play().catch(()=>setPlaying(false)):audio.pause()},[playing,state?.phase]);
  const particles=useMemo(()=>Array.from({length:54},(_,i)=>({left:`${(i*37)%100}%`,delay:`${(i%12)*-.35}s`,duration:`${3.5+(i%7)*.4}s`,color:['#f59e0b','#38bdf8','#ef4444','#10b981','#f8fafc'][i%5]})),[]);
  if(!state)return <main className="board board-enhanced"><div className="board-connect"><span className="live-dot"/>전광판 연결 대기 중<p>게임 사전 설정을 완료하면 이 화면에 자동으로 연결됩니다.</p></div></main>;
  const time=`${String(Math.floor(state.remainingSeconds/60)).padStart(2,'0')}:${String(state.remainingSeconds%60).padStart(2,'0')}`,results=state.revealed!;
  const player=results?.players.find(x=>x.id===selected),sheet=results?.submissions.find(x=>x.playerId===selected);
  return <main className={`board board-enhanced ${state.phase==='results'?'celebration':''}`}><audio id="board-bgm" loop src={`${A}audio/bgm/${state.phase==='results'?'bgm-final-ranking.mp3':state.phase==='active'?'bgm-gameplay.mp3':'bgm-waiting.mp3'}`}/>{state.phase==='results'&&<div className="confetti-field">{particles.map((p,i)=><i key={i} style={{left:p.left,animationDelay:p.delay,animationDuration:p.duration,background:p.color}}/>)}</div>}{state.phase!=='results'&&<><div className={`board-clock ${state.phase==='submission'?'submission-message':''}`}>{state.phase==='submission'?'결과지 제출 중':time}</div><div className="board-players">{state.players.map((p,i)=><article className={p.submitted?'submitted':''}><img src={avatarPath(i)}/><strong>{p.name}</strong>{p.submitted&&<span>결과 제출 완료</span>}</article>)}</div><div className="board-rooms">{state.rooms.map(room=>{const busy=room.status!=='waiting';return <article className={busy?'busy':'available'}><b><i/>{`콘택트룸 ${room.id}`}</b><span>{room.status==='waiting'?'대기 중':room.status==='result'?room.result:'사용 중'}</span></article>})}</div></>}{state.phase==='results'&&results&&<section className="board-ranking"><h1>최종 결과</h1>{[...results.players].sort((a,b)=>b.score-a.score).map((p,i)=><button onClick={()=>setSelected(p.id)}>{i<3&&<img src={`${A}images/medals/medal-${['1st','2nd','3rd'][i]}.png`}/>}<b>{i+1}위</b><img className="rank-avatar" src={avatarPath(state.players.findIndex(x=>x.id===p.id))}/><strong>{p.name}</strong><em>{p.score}점</em><span>자세히 보기 ↗</span></button>)}</section>}<button className="audio-control" onClick={()=>setPlaying(!playing)}>{playing?'Ⅱ':'▶'} BGM</button>{player&&<div className="overlay"><section className="modal board-detail"><button className="x" onClick={()=>setSelected(undefined)}>×</button><h2>{player.name} 결과</h2><div className="secret">비밀 숫자<b>{player.secretNumber}</b></div><h3>제출한 예상</h3><div className="guess-record"><p>내 번호 예상 <b>{sheet?.ownGuess??'-'}</b></p>{Object.entries(sheet?.guesses||{}).map(([id,value])=><p>{results.players.find(x=>x.id===id)?.name} <b>{value}</b></p>)}</div><h3>티켓 사용·활동 로그</h3>{state.logs.filter(log=>log.playerIds?.includes(player.id)).map(log=><p>{new Date(log.at).toLocaleTimeString()} · {log.text}</p>)}</section></div>}</main>}
