import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { createGame } from './game';
import type { Difficulty } from './types';

const A='/assets/';
export const AVATAR_FILES=['avatar-1-Raccoon.png','avatar-2-parrot.png','avatar-3-turtle.png','avatar-4-lion.png','avatar-5-tiger.png','avatar-6-wolf.png','avatar-7-dragon.png','avatar-8-shark.png','avatar-9-panda.png','avatar-10-bear.png','avatar-11-fox.png','avatar-12-owl.png','avatar-13-rabbit.png','avatar-14-frog.png','avatar-15-monkey.png','avatar-16-butterfly.png','avatar-17-bee.png'];
export const avatarPath=(i:number)=>`${A}images/avatars/${AVATAR_FILES[i%AVATAR_FILES.length]}`;

const sfx:Record<string,string>={default:'sfx-button-default.wav',countdown:'sfx-countdown.wav',selected:'sfx-card-selected.wav',start:'sfx-game-start.wav',contact:'sfx-contact-start.wav',result:'sfx-contact-result.wav',move:'sfx-card-movement.wav',process:'sfx-calculation-processing.wav'};
export function playSfx(kind:keyof typeof sfx='default'){const audio=new Audio(`${A}audio/sfx/${sfx[kind]}`);audio.volume=.55;void audio.play().catch(()=>{});}
export function SoundLayer(){useEffect(()=>{const click=(e:MouseEvent)=>{const button=(e.target as HTMLElement).closest('button,a.button,a.display-launch');if(!button)return;const text=button.textContent||'';playSfx(/결과 공개/.test(text)?'result':/시크릿 넘버 시작/.test(text)?'start':/티켓|콘택트/.test(text)?'contact':/카드 선택/.test(text)?'selected':'default')};document.addEventListener('click',click);return()=>document.removeEventListener('click',click)},[]);return null}

function Shell({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}){return <div className="overlay"><section className="modal enhanced-modal"><button className="x" onClick={onClose}>×</button><h2>{title}</h2>{children}</section></div>}

const tickets=[
  ['plus','더하기','두 플레이어의 비밀 숫자를 더한 결과를 수의 범위로 확인합니다.'],
  ['multiply','곱하기','두 비밀 숫자를 곱한 값의 일의 자리를 확인합니다.'],
  ['divide','나누기','큰 수를 작은 수로 나눈 뒤 나머지를 버린 몫을 확인합니다.'],
  ['zero','0 개수','두 비밀 숫자 사이에 등장하는 숫자 0의 개수를 확인합니다.']
];
export function GuideEnhanced({onClose}:{onClose:()=>void}){const [page,setPage]=useState(0);const slides=[
  <div className="guide-copy"><h3>숨겨진 숫자를 추리하고 최후의 승자가 되어라.</h3><p>모든 플레이어는 누구에게도 공개되지 않는 비밀 숫자 하나를 배정받습니다.</p><p>다른 플레이어와 콘택트하고 제한된 티켓으로 단서를 수집합니다.</p><p>자신의 숫자와 친구들의 숫자를 정확하게 추리하여 점수를 획득하세요.</p><strong>모든 결과를 합산했을 때 가장 높은 점수를 얻은 플레이어가 우승합니다.</strong></div>,
  <div className="guide-copy"><h3>같은 티켓을 선택하고 단서를 획득하세요.</h3><p>두 플레이어가 콘택트룸의 태블릿에 각각 접속합니다.</p><p>서로 같은 종류의 티켓을 선택해 제출하면 계산 결과가 수의 범위로 공개됩니다.</p><div className="guide-tickets">{tickets.map(([file,name,desc])=><article><img src={`${A}images/tickets/ticket-${file}.png`}/><b>{name}</b><span>{desc}</span></article>)}</div></div>,
  <div className="guide-copy operation-guide"><h3>교사 운영 순서</h3><ol><li><b>사전 설정</b><span>플레이어, 게임 시간, 숫자 난이도, 콘택트룸 수를 설정합니다.</span></li><li><b>교실 준비</b><span>전광판을 열고 앞문·뒷문 바깥에 책상과 태블릿 2대씩 콘택트룸을 설치하세요.</span></li><li><b>카드 배정</b><span>게임을 시작하면 카드가 자동 배정됩니다. 누구도 카드 숫자를 확인할 수 없습니다.</span></li><li><b>자유 추리</b><span>하 1~30 · 중 1~60 · 상 1~100 범위에서 티켓 단서를 모아 숫자를 추리합니다.</span></li><li><b>제출·집계</b><span>종료 후 각 태블릿에서 결과지를 제출하고 전원 제출 후 결과를 공개합니다.</span></li></ol><div className="score-rule">내 번호 정답 +5점 · 친구 번호 정답 +3점 · 다른 친구가 내 번호를 맞히면 -1점</div></div>,
  <div className="guide-copy"><h3>게임 종료와 결과 공개</h3><p>교사가 게임 종료를 누르면 타이머와 콘택트가 중지됩니다.</p><p>화면에 생성된 링크 또는 QR 코드로 학생 결과지를 제출합니다.</p><p>모든 제출을 확인한 뒤 결과 공개 버튼을 누릅니다.</p><strong>전광판에서 비밀 숫자, 점수와 최종 순위를 함께 확인합니다.</strong></div>,
  <div className="guide-copy"><h3>방송 속 게임을 참고해 보세요.</h3><p>더 자세한 게임 진행 방식은 유튜브에서 ‘데블스 플랜 시크릿 넘버’를 검색해 참고해 주세요.</p><a className="button" target="_blank" href="https://www.youtube.com/results?search_query=데블스+플랜+시크릿+넘버">유튜브에서 찾아보기 ↗</a></div>
];return <Shell title={['게임의 목표','콘택트와 티켓','교사 게임 운영','결과 제출과 공개','참고 영상'][page]} onClose={onClose}><div className="guide-number">{page+1}</div>{slides[page]}<div className="guide-dots">{slides.map((_,i)=><i className={i===page?'on':''}/>)}</div><div className="pager"><button disabled={!page} onClick={()=>setPage(page-1)}>이전</button><span>{page+1} / 5</span><button onClick={()=>page===4?onClose():setPage(page+1)}>{page===4?'닫기':'다음'}</button></div></Shell>}

export function IntroEnhanced({onDone,onClose}:{onDone:()=>void;onClose:()=>void}){const [page,setPage]=useState(0);const [ok,setOk]=useState(false);const concepts=[['이상','기준 수 포함','그보다 큰 수','10 이상 → 10, 11, 12…'],['이하','기준 수 포함','그보다 작은 수','10 이하 → …8, 9, 10'],['초과','기준 수 미포함','그보다 큰 수','10 초과 → 11, 12, 13…'],['미만','기준 수 미포함','그보다 작은 수','10 미만 → …7, 8, 9']];const quizzes:[string,string[],string,string][]=[['24 이상 25 미만인 자연수는?',['23','24','25'],'24','24는 이상에 포함되고 25는 미만에 포함되지 않습니다.'],['36 초과 38 미만인 자연수는?',['36','37','38'],'37','36과 38은 모두 포함되지 않으므로 37입니다.'],['51 초과 52 이하인 자연수는?',['51','52','53'],'52','51은 초과라 제외되고 52는 이하라 포함됩니다.']];return <Shell title="수의 범위를 이해하라" onClose={onClose}><button className="skip" onClick={onDone}>인트로 건너뛰기</button>{page===0?<div className="concepts">{concepts.map(([name,a,b,example])=><article><b>{name}</b><span>{a}<br/>{b}</span><em>{example}</em></article>)}</div>:page<4?<div className="quiz"><h3>{quizzes[page-1][0]}</h3>{quizzes[page-1][1].map(answer=><button onClick={()=>setOk(answer===quizzes[page-1][2])}>{answer}</button>)}{ok&&<p className="success">정답입니다. {quizzes[page-1][3]}</p>}</div>:<div className="crawl-stage"><div className="final-crawl"><p>수의 범위를 모두 알았다면<br/>이제 게임을 시작하지.</p><strong>비밀 숫자를 맞히지 못한다면<br/>넌 이곳에서 빠져나갈 수 없다!!</strong></div></div>}<div className="pager"><button disabled={!page} onClick={()=>{setPage(page-1);setOk(false)}}>이전</button>{page===4?<button className="primary" onClick={onDone}>시크릿 넘버 시작</button>:<button disabled={page>0&&!ok} onClick={()=>{setPage(page+1);setOk(false)}}>다음</button>}</div></Shell>}

const difficultyInfo:Record<Difficulty,string>={high:'비밀 숫자 1~100 · 추론 단계가 많아 6학년 이상에게 추천합니다.',medium:'비밀 숫자 1~60 · 적절한 난이도로 4~5학년에게 추천합니다.',low:'비밀 숫자 1~30 · 수의 범위를 처음 배우는 중·저학년에게 추천합니다.'};
export function SetupEnhanced(){const nav=useNavigate();const [names,setNames]=useState('고양이\n강아지\n토끼\n여우\n사자\n거북이');const [minutes,setMinutes]=useState(60);const [difficulty,setDifficulty]=useState<Difficulty>('medium');const [rooms,setRooms]=useState(2);const list=names.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const start=()=>{if(list.length<2)return;sessionStorage.setItem('secret-number-game',JSON.stringify(createGame(list,minutes,difficulty,rooms)));nav('/host')};return <main className="page setup-page"><div className="setup-titlebar"><h1>게임 사전 설정</h1><div><button onClick={()=>nav('/')}>메인화면 (게임 초기화)</button><a className="display-launch" href="/board" target="_blank">게임 전광판 페이지 활성화 ↗</a></div></div><section className="display-prep"><div><small>DISPLAY</small><h2>먼저 전광판을 준비하세요</h2><p>별도의 창에서 게임 진행 상황이 연동됩니다.</p></div><a className="display-launch" href="/board" target="_blank">게임 전광판 페이지 활성화 ↗</a></section><div className="setup-grid"><section className="panel registration"><small>PLAYER REGISTRATION</small><h2>플레이어 등록 <em>{list.length}/30</em></h2><p>한 줄에 한 명씩 이름을 입력하세요. Enter로 다음 플레이어를 등록할 수 있습니다.</p><textarea value={names} onChange={e=>setNames(e.target.value)} /><strong>모든 난이도에서 최대 30명까지 등록할 수 있습니다.</strong></section><section className="panel options"><small>GAME TIME</small><h2>게임 시간</h2><label><input className="time-input" type="number" min="5" max="180" value={minutes} onChange={e=>setMinutes(+e.target.value)}/><span>분</span></label><p>60분 정도가 적당합니다.<br/>학급 상황에 맞게 타이머를 조정해주세요.</p><hr/><small>NUMBER LEVEL</small><h2>번호 난이도</h2><div className="seg level-seg">{([['high','상'],['medium','중'],['low','하']] as const).map(([value,label])=><button title={difficultyInfo[value]} data-tip={difficultyInfo[value]} className={difficulty===value?'on':''} onClick={()=>setDifficulty(value)}>{label}</button>)}</div><p className="hover-help">버튼에 마우스를 올리면 난이도 설명이 나타납니다.</p><hr/><small>CONTACT ROOMS</small><h2>콘택트룸 수</h2><div className="seg room-seg">{[1,2,3].map(value=><button className={rooms===value?'on':''} onClick={()=>setRooms(value)}>{value}</button>)}</div><p>앞문과 뒷문 바깥에 설치할 수 있는 공간 수를 고려하세요.</p></section></div><button className="primary next setup-next" onClick={start}>다음 · 비밀 카드 배정</button></main>}
