import { useEffect,useMemo,useRef,useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { ClientNetwork } from './network';
import { avatarPath,playSfx } from './enhancements';
import type { ClientMessage,ContactRoom,PublicState,TicketType } from './types';

const A='/assets/';const uid=()=>crypto.randomUUID();
export default function StationEnhanced(){
  const[q]=useSearchParams(),code=q.get('code')||'',roomId=+(q.get('room')||1);
  const device=useMemo(()=>sessionStorage.getItem(`station-${code}-${roomId}`)||uid(),[]);
  const[state,setState]=useState<PublicState|null>(null),[room,setRoom]=useState<ContactRoom>(),[seat,setSeat]=useState<number>();
  const[pendingPlayer,setPendingPlayer]=useState<string>(),[confirmed,setConfirmed]=useState(false),[connected,setConnected]=useState(false),[notice,setNotice]=useState('');
  const[resultSeconds,setResultSeconds]=useState(5);const net=useRef<ClientNetwork|undefined>(undefined);const resultKey=useRef(0);
  useEffect(()=>{sessionStorage.setItem(`station-${code}-${roomId}`,device);const n=new ClientNetwork(code,{type:'HELLO',role:'station',deviceId:device,roomId});net.current=n;n.onStatus=setConnected;n.onMessage=m=>{if(m.type==='WELCOME'){setState(m.state);setSeat(m.seat);setRoom(m.state.rooms.find(r=>r.id===roomId))}if(m.type==='STATE'){setState(m.state);setRoom(m.state.rooms.find(r=>r.id===roomId))}if(m.type==='ERROR')setNotice(m.message);if(m.type==='ACK'&&m.message)setNotice(m.message);if(m.type==='ACK'&&!m.ok)setNotice(m.message||'처리할 수 없습니다.')};return()=>n.destroy()},[]);
  useEffect(()=>{if(room?.status!=='result'||room.updatedAt===resultKey.current)return;resultKey.current=room.updatedAt;setResultSeconds(5);playSfx('result');const timer=setInterval(()=>setResultSeconds(value=>{if(value<=1){clearInterval(timer);net.current?.send({type:'RESET_ROOM',roomId,requestId:uid()});setConfirmed(false);setPendingPlayer(undefined);return 0}return value-1}),1000);return()=>clearInterval(timer)},[room?.status,room?.updatedAt]);
  const send=(message:ClientMessage)=>net.current?.send(message);const mySeat=seat===undefined?undefined:room?.seats[seat];
  function confirmPlayer(){if(seat===undefined||!pendingPlayer)return;send({type:'SELECT_PLAYER',roomId,seat,playerId:pendingPlayer,requestId:uid()});setConfirmed(true);setPendingPlayer(undefined)}
  if(!code)return <main className="station"><div className="waiting">게임 코드가 필요합니다.</div></main>;
  if(state&&state.phase!=='active')return <main className="station"><header><h1>콘택트룸 {roomId}</h1></header><div className="station-ended">게임이 종료되었습니다.</div></main>;
  if(notice.includes('이미 태블릿 2대'))return <main className="station"><header><h1>콘택트룸 {roomId}</h1></header><div className="station-ended denied">접속할 수 없습니다.<small>{notice}</small></div></main>;
  return <main className="station"><header><div><h1>콘택트룸 {roomId}</h1><small>태블릿 {seat===0?'A':seat===1?'B':'·'} 좌석</small></div><span className={connected?'online':'offline'}>{connected?'연결됨':'연결 중'}</span></header>{notice&&<div className="notice" onClick={()=>setNotice('')}>{notice}</div>}{seat===undefined?<div className="waiting">교사 운영 페이지와 연결하고 있습니다.</div>:room?.status==='result'?<section className="result-screen"><div className="result-progress"><i style={{width:`${resultSeconds*20}%`}}/></div><small>{resultSeconds}초 후 플레이어 선택 화면으로 돌아갑니다.</small><span>연산 결과</span><b>{room.result}</b></section>:!confirmed?<section className="station-step"><div className="step-label">STEP 1 · 플레이어 선택</div><h2>플레이어를 선택하세요.</h2><p>이 태블릿에서는 한 명만 선택합니다.</p><div className="station-players">{state?.players.map((player,index)=><button onClick={()=>setPendingPlayer(player.id)}><img src={avatarPath(index)}/>{player.name}</button>)}</div></section>:<section className="station-step ticket-step"><div className="step-label">STEP 2 · 티켓 선택</div><h2>상대방과 같은 티켓을 선택하세요.</h2><div className="selected-player"><img src={avatarPath(state?.players.findIndex(x=>x.id===mySeat?.playerId)||0)}/><b>{state?.players.find(x=>x.id===mySeat?.playerId)?.name}</b></div><div className="tickets">{(['plus','multiply','divide','zero'] as TicketType[]).map(ticket=><button className={mySeat?.ticket===ticket?'on':''} onClick={()=>send({type:'SELECT_TICKET',roomId,seat,ticket,requestId:uid()})}><img src={`${A}images/tickets/ticket-${ticket}.png`}/><span>{{plus:'더하기',multiply:'곱하기',divide:'나누기',zero:'0 개수'}[ticket]}</span></button>)}</div><div className="station-actions"><button onClick={()=>setConfirmed(false)}>플레이어 다시 선택</button><button className="primary" disabled={!mySeat?.ticket||room?.status==='processing'} onClick={()=>{setNotice('상대방의 티켓 제출을 기다리고 있습니다.');send({type:'SUBMIT_CONTACT',roomId,requestId:uid()})}}>{room?.status==='processing'?'연산 중…':'티켓 제출'}</button></div></section>}{pendingPlayer&&<div className="overlay"><section className="modal player-confirm"><h2>해당 플레이어가 맞습니까?</h2><p>다른 플레이어로 접속할 경우 공정한 게임을 방해할 수 있습니다.</p><div className="pager"><button onClick={()=>setPendingPlayer(undefined)}>취소</button><button className="primary" onClick={confirmPlayer}>확인</button></div></section></div>}</main>
}
